backend:
    name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
    branch: add-short-event-descriptions # Branch to update
    repo: umcptasa/19-20website # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets
public_folder: assets

collections:
    - name: events
      label: "Events"
      folder: "content/events"
      create: true # whether or not new events can be added
      slug: "{{slug}}" # unique URL for the created event
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Date", name: "date", widget: "datetime" }
          - { label: "Cover Image", name: "imgsrc", widget: "image" }
          - {
                label: "Category",
                name: "category",
                widget: "hidden",
                default: "event",
            }
          - {
                label: "Pinned",
                name: "pinned",
                widget: "boolean",
                required: false,
                default: false,
                hint: "Pinned to front page and events page",
            }
          - {
                label: "Tags",
                name: "tags",
                widget: "relation",
                collection: "options",
                file: "event-tags",
                hint: "New tags can be added in the Editable Options collection",
                valueField: "options.*",
                searchFields: ["options.*"],
                default: "select",
                multiple: true,
            }

          - {
                label: "Facebook Event Page Link",
                name: "link",
                widget: "string",
                minimal: true,
            }
          - {
                label: "Blurb",
                name: "blurb",
                widget: "markdown",
                required: false,
                hint: "Optional short description used in the previews on the front page and all events page. If not used, then the full description is used instead",
            }
          - {
                label: "Description",
                name: "body",
                widget: "markdown",
                hint: "Longer description shown on the full individual event page",
            }
    - name: bios
      identifier_field: name
      label: "Bios"
      folder: "content/bios"
      create: true
      fields:
          - { label: "Name", name: "name", widget: "string" }
          - {
                label: "Category",
                name: "category",
                widget: "hidden",
                default: "bio",
            }
          - {
                label: "Profile Picture",
                name: "imgsrc",
                widget: "image",
                hint: "Square images are preferred!",
            }

          # This could be changed to a select widget that provides a dropdown of possible positions.
          # You would have to update the list of positions in this file though
          # https://www.netlifycms.org/docs/widgets/#select
          - {
                label: "Position",
                name: "position",
                widget: "relation",
                collection: "options",
                file: "bio-order",
                hint: "New positions can be added in the Editable Options collection",
                valueField: "options.*",
                searchFields: ["options.*"],
                default: "select",
            }

          - {
                label: "Major(s)",
                name: "majors",
                widget: "list",
                required: true,
                allow_add: true,
                hint: "Separate multiple majors with commas. Spaces after commas will be automatically added",
            }
          - {
                label: "Description",
                name: "body",
                widget: "markdown",
                required: false,
                default: "No bio",
            }
    - name: options
      identifier_field: title
      label: "Editable Options"
      create: false
      folder: "content/options"
      fields:
          - { label: "Title", name: "title", widget: "string" }
          - {
                label: "Category",
                name: "category",
                widget: "hidden",
                default: "options",
            }
          - {
                label: "Options",
                name: "options",
                allow_add: true,
                widget: "list",
                collapsed: false,
                hint: "Order of this list determines order on site where applicable. Spaces after commas will be automatically added",
            }
